import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import about from "./_app";
import Link from "next/link";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>home</h1>
      <Link href="/about">
        <a> about</a>
      </Link>
      <Link href="/products">
        <a> products</a>
      </Link>
      <about />
    </div>
  );
}
